# Generated by Django 6.1 on 2026-09-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default='default', max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('expression', models.CharField(default='normal', max_length=32)),
                ('animation', models.CharField(default='none', max_length=32)),
                ('thinking', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(choices=[('identity', 'Identity / Personal Info'), ('preference', 'Preference / Like / Dislike'), ('project', 'Project / Task Info'), ('habit', 'Habit / Schedule'), ('general', 'General Fact')], db_index=True, default='general', max_length=32)),
                ('content', models.TextField(help_text='The factual statement or memory snippet')),
                ('confidence', models.FloatField(default=1.0, help_text='Confidence score from 0.0 to 1.0')),
                ('source', models.CharField(default='conversation', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.TextField(help_text='JSON string or plain text preference value')),
                ('category', models.CharField(db_index=True, default='general', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
    ]
