# Generated by Django 6.1 on 2026-09-06 17:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, unique=True)),
                ('user_name', models.CharField(default='User', max_length=64)),
                ('active_app', models.CharField(blank=True, default='', max_length=128)),
                ('idle_seconds', models.IntegerField(default=0)),
                ('total_messages', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('device_type', models.CharField(default='ESP32', max_length=32)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('battery_pct', models.IntegerField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('firmware_version', models.CharField(default='1.0.0', max_length=32)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
