# Generated by Django 6.1 on 2026-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, default='default', max_length=64)),
                ('project_id', models.CharField(db_index=True, default='default', max_length=64)),
                ('user_id', models.CharField(default='default', max_length=64)),
                ('request_input', models.TextField()),
                ('status', models.CharField(db_index=True, default='pending', max_length=32)),
                ('is_valid', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=2)),
                ('final_output', models.TextField(blank=True, default='')),
                ('evaluation_result', models.JSONField(blank=True, default=dict)),
                ('retrieved_sources', models.JSONField(blank=True, default=list)),
                ('plan', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
